# Generated by Django 4.2.19 on 2025-03-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessroutine',
            name='exercise',
        ),
    ]
