# Generated by Django 4.2.19 on 2025-03-03 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_remove_fitnessroutine_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta)),
                ('image', models.CharField(max_length=300, null=True)),
                ('exercise', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routines.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='fitnessroutine',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routines.userexercise'),
        ),
    ]
