# Generated by Django 4.2.19 on 2025-03-03 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_userexercise_fitnessroutine_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
