# Generated by Django 4.2.19 on 2025-02-28 00:08

from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations


def preload_exercises(apps, schema_editor):

    exercise = apps.get_model('routines', 'Exercise')

    exercises = [
        ('BO', 'Bent-over Rows', 'UB'),
        ('CS', 'Cable Rows', 'UB'),
    ]

    for key, name, category in exercises:
        exercise.objects.create(key=key, name=name, category=category)


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_preload_excercise'),
    ]

    operations = [
        migrations.RunPython(preload_exercises),
    ]
