# Generated by Django 4.2.19 on 2025-03-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_userexercise_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessroutine',
            name='routine_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
