# Generated by Django 4.2.19 on 2025-03-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0005_fitnessroutine_routine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
