# Generated by Django 4.2.19 on 2025-03-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0006_userexercise_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
