# Generated by Django 4.2.19 on 2025-03-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0007_exercise_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
