# Generated by Django 4.2.19 on 2025-03-06 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0010_update_exercise_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessroutine',
            name='routine_duration',
        ),
        migrations.RemoveField(
            model_name='fitnessroutine',
            name='routine_reps',
        ),
        migrations.RemoveField(
            model_name='fitnessroutine',
            name='routine_set',
        ),
        migrations.AddField(
            model_name='fitnessroutine',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
