# Generated by Django 4.2.19 on 2025-03-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0011_remove_fitnessroutine_routine_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessroutine',
            name='day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=10),
        ),
    ]
