# Generated by Django 4.2.19 on 2025-03-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0012_fitnessroutine_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessroutine',
            name='day',
        ),
    ]
