# Generated by Django 4.2.19 on 2025-03-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_nutritioninfo_alter_mealplan_nutrient'),
        ('routines', '0013_remove_fitnessroutine_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NutritionInfo',
        ),
    ]
