# Generated by Django 4.2.19 on 2025-02-28 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclaimer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclaimer', models.CharField(max_length=255)),
                ('exercise', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('frequency', models.CharField(max_length=255)),
                ('justification', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fitnessrecommendation',
            name='fitness_goal',
        ),
        migrations.RemoveField(
            model_name='fitnessrecommendation',
            name='height',
        ),
        migrations.RemoveField(
            model_name='fitnessrecommendation',
            name='sex',
        ),
        migrations.CreateModel(
            name='UserFitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], default=('P', 'Prefer not to say'), max_length=20)),
                ('fitness_goal', models.CharField(default='WEI', max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fitnessrecommendation',
            name='user_fitness',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fitness.userfitness'),
        ),
        migrations.AlterField(
            model_name='fitnessrecommendation',
            name='recommendation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fitness.recommendation'),
        ),
        migrations.DeleteModel(
            name='Fitness',
        ),
    ]
