# Generated by Django 4.2.19 on 2025-03-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_fitnessplan_recommendation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='disclaimer',
        ),
        migrations.AddField(
            model_name='fitnessrecommendation',
            name='disclaimer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
