# Generated by Django 4.2.19 on 2025-03-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_remove_recommendation_disclaimer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfitness',
            name='fitness_goal',
            field=models.CharField(choices=[('WEI', 'Weight Loss'), ('MUS', 'Muscle Gain (Hypertrophy)'), ('INC', 'Increase Strength'), ('IMP', 'Improve Endurance'), ('FLE', 'Flexibility and Mobility'), ('CAR', 'Improve Cardiovascular Health'), ('FAT', 'Fat Loss and Lean Muscle Tone'), ('BOD', 'Bodybuilding'), ('SPO', 'Sports Performance'), ('POS', 'Post-Surgery Rehab and Recovery'), ('IMP', 'Improve Posture'), ('SPE', 'Increase Speed and Agility'), ('FUN', 'Functional Fitness (everyday movement and strength)'), ('MEN', 'Improve Mental Health (e.g., reduce stress, anxiety)'), ('MAI', 'Maintain a Healthy Lifestyle'), ('IMB', 'Improved Balance and Coordination'), ('COR', 'Increase Core Strength'), ('STA', 'Improve Stamina'), ('HEA', 'Health Maintenance (keep body in good shape)'), ('TRA', 'Training for a Specific Event (e.g., marathon, triathlon, etc.)')], default='WEI', max_length=80),
        ),
    ]
