# Generated by Django 4.2.19 on 2025-03-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
        ('meal', '0002_insert_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='nutrient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routines.nutritioninfo'),
        ),
    ]
