# Generated by Django 4.2.19 on 2025-03-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
        ('meal', '0003_mealplan_nutrient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='nutrient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.nutritioninfo'),
        ),
    ]
