# Generated by Django 4.2.19 on 2025-03-09 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_nutritioninfo_alter_mealplan_nutrient'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutrientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='meal.nutrientcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('valid', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('other_nutrients', models.TextField(blank=True, null=True)),
                ('nutrients', models.ManyToManyField(blank=True, related_name='food_items', to='meal.nutrient')),
            ],
        ),
    ]
