# Generated by Django 4.2.19 on 2025-03-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_nutrientcategory_nutrient_fooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='nutrients',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='category',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='error',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='item',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='macronutrients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='minerals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='vitamins',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='other_nutrients',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='valid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mealrecommendation',
            name='recommended_meal',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='summary',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='NutrientCategory',
        ),
    ]
