# Generated by Django 4.2.19 on 2025-03-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_remove_fooditem_error_message_remove_fooditem_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='error',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='nutrient',
        ),
    ]
