# Generated by Django 4.2.19 on 2025-03-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_remove_fooditem_error_remove_mealplan_meal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='food_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.fooditem'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='food_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
