# Generated by Django 4.2.19 on 2025-03-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_mealplan_food_item_mealplan_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='other_nutrients',
            field=models.CharField(blank=True, default='', max_length=850, null=True),
        ),
    ]
