# Generated by Django 4.2.19 on 2025-03-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0010_alter_fooditem_other_nutrients'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='meal_plan_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
