# Generated by Django 4.2.19 on 2025-03-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0011_mealplan_meal_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='meal_plan_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
