# Generated by Django 4.2.19 on 2025-03-11 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0012_alter_mealplan_meal_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='meal_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
