# Generated by Django 4.2.19 on 2025-02-28 00:08

from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations


# def preload_exercises(apps, schema_editor):
#
#     exercise = apps.get_model('routines', 'Exercise')
#
#     exercises = [
#         ('BP', 'Bench Press', 'UB'),
#         ('PP', 'Push Press', 'UB'),
#         ('OP', 'Overhead Press', 'UB'),
#         ('PU', 'Pull-ups', 'UB'),
#         ('LP', 'Lat Pulldown', 'UB'),
#         ('BR', 'Bent-over Rows', 'UB'),
#         ('DB', 'Dumbbell Press', 'UB'),
#         ('DI', 'Dips', 'UB'),
#         ('CO', 'Cable Rows', 'UB'),
#         ('SQ', 'Squats', 'LB'),
#         ('DL', 'Deadlifts', 'LB'),
#         ('RD', 'Romanian Deadlifts', 'LB'),
#         ('FS', 'Front Squats', 'LB'),
#         ('BS', 'Bulgarian Split Squats', 'LB'),
#         ('LC', 'Leg Curls', 'LB'),
#         ('LE', 'Leg Extensions', 'LB'),
#         ('CL', 'Calf Raises', 'LB'),
#         ('PL', 'Planks', 'CO'),
#         ('HL', 'Hanging Leg Raises', 'CO'),
#         ('RT', 'Russian Twists', 'CO'),
#         ('CR', 'Cable Rotations', 'CO'),
#         ('SU', 'Sit-ups', 'CO'),
#         ('TW', 'Toe-to-Bar', 'CO'),
#         ('HH', 'Hollow Holds', 'CO'),
#         ('BJ', 'Box Jumps', 'EX'),
#         ('SJ', 'Sled Push', 'EX'),
#         ('KB', 'Kettlebell Swings', 'EX'),
#         ('TF', 'Tire Flips', 'EX'),
#         ('FR', 'Farmer’s Carries', 'EX'),
#         ('MB', 'Med Ball Slams', 'EX'),
#         ('SP', 'Sprint Intervals', 'EX'),
#         ('RW', 'Rowing', 'CM'),
#         ('JR', 'Jump Rope', 'CM'),
#         ('YT', 'Yoga / Stretching', 'CM'),
#         ('SW', 'Swimming', 'CM'),
#         ('TR', 'TRX Rows', 'CM'),
#         ('BC', 'Battle Ropes', 'CM'),
#         ('BR', 'Burpees', 'CM'),
#     ]
#
#     for key, name, category in exercises:
#         exercise.objects.create(key=key, name=name, category=category)
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('routines', '0001_initial'),
#     ]
#
#     operations = [
#         migrations.RunPython(preload_exercises),
#     ]
