# Generated by Django 4.2.19 on 2025-03-01 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0049_alter_otp_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(db_comment='When the OTP can no longer be accepted. Default is 5 minutes after when it was created.', default=datetime.datetime(2025, 3, 1, 17, 36, 52, 735, tzinfo=datetime.timezone.utc)),
        ),
    ]
