name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - shell: bash
      env:
        DB_NAME: $DB_NAME
        DB_PASSWORD: $DB_PASSWORD
        DB_USERNAME: $DB_USERNAME
        DB_HOST: $DB_HOST
        GEMINI_KEY: ${{ env.GEMINI_KEY }}
      run: |
        echo "Super secret is: $DB_NAME"
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
